2024-11-14 22:49:42,460 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\urban\pythonProject\tests_12_4.py", line 20, in test_run
    tmp = module_12_4.Runner(123)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\urban\pythonProject\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-14 22:49:42,462 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\urban\pythonProject\tests_12_4.py", line 10, in test_walk
    tmp = module_12_4.Runner('Denis', -10)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\PycharmProjects\urban\pythonProject\module_12_4.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
